### ISSUE TITLE
The repository is missing license for the code

### ISSUE THREAD

**Issue by metan-ucw** [andrewerrington/meter#2]
Thanks for the nice script I'm going to use it to create a quadratic scale for a power meter.

However the repository is missing a license, feel free to choose from:

https://opensource.org/licenses

If you want the code to be public domain MIT would be likely the best choice. If you want to avoid anybody building a closed source product based on the source code you should go for GPL.

**Comment by andrewerrington** [comment]
Done! I decided on GPL v3.
